import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from './gpts/component/Header'
import Footer from './gpts/component/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/png" sizes="16x16" href="/logo.png" />
      </head>
      <body className={inter.className}>
        <main>
          <Header />
          {children}
          <Footer />
        </main>

        <script
          defer
          data-domain="gpts.works"
          src="https://plausible.io/js/script.js"
        ></script>
      </body>
    </html>
  );
}
